---
# - name: Download gitlab rpm file from internet
#   get_url:
#      url=https://packages.gitlab.com/gitlab/gitlab-ce/packages/el/7/gitlab-ce-12.0.3-ce.0.el7.x86_64.rpm/download.rpm
#      dest=/home

 - name: Copy gitlab-ce rpm file from ansible server to gitlab server
   copy:
     src={{ gitlabrpmlocalpath }}
     dest=/home/gitlab-ce-12.0.3-ce.0.el7.x86_64.rpm

 - name: Download gitlab-ce installation script
   shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash

 - name: Installing gitlab. THIS WILL TAKE MORE TIME.IT CAN TAKE 15 MINS TO 45 MINS
   shell: EXTERNAL_URL="{{ inventory_hostname }}" rpm -ivh /home/gitlab-ce-12.0.3-ce.0.el7.x86_64.rpm
